/**
 * Base schema classes shared by Lucid models.
 *
 * Normally auto-generated by `node ace schema:generate`, but schemaGeneration
 * is disabled in config/database.ts to avoid a chicken-and-egg problem:
 *
 *   migration:rollback → drops tables → schema:generate finds 0 tables →
 *   overwrites this file with empty content → migration:run can't boot
 *   because models import from this now-empty file.
 *
 * To regenerate after adding new migrations:
 *   1. npm run db:fresh              ← applies migrations (this file stays intact)
 *   2. node ace schema:generate      ← DB now has tables → correct output
 */

import { DateTime } from 'luxon'
import { BaseModel, column } from '@adonisjs/lucid/orm'

// ──────────────────────────────────────────────────────────────────────────────
// users
// ──────────────────────────────────────────────────────────────────────────────
export class UserSchema extends BaseModel {
  @column({ isPrimary: true })
  declare id: number

  @column()
  declare fullName: string | null

  @column()
  declare email: string

  @column({ serializeAs: null })
  declare password: string

  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime

  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

// ──────────────────────────────────────────────────────────────────────────────
// products
// ──────────────────────────────────────────────────────────────────────────────
export class ProductSchema extends BaseModel {
  @column({ isPrimary: true })
  declare id: string

  @column()
  declare name: string

  @column()
  declare description: string | null

  /** Price in cents — e.g. 4990 = R$49,90 */
  @column()
  declare price: number

  @column()
  declare imageUrl: string | null

  @column()
  declare category: string

  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime

  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

// ──────────────────────────────────────────────────────────────────────────────
// stocks
// ──────────────────────────────────────────────────────────────────────────────
export class StockSchema extends BaseModel {
  @column({ isPrimary: true })
  declare id: string

  @column()
  declare productId: string

  @column()
  declare quantity: number

  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime

  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

// ──────────────────────────────────────────────────────────────────────────────
// orders
// ──────────────────────────────────────────────────────────────────────────────
export class OrderSchema extends BaseModel {
  @column({ isPrimary: true })
  declare id: string

  @column()
  declare customerId: string

  @column()
  declare productId: string

  @column()
  declare productName: string

  @column()
  declare quantity: number

  /** Unit price in cents */
  @column()
  declare unitPrice: number

  /** Total in cents */
  @column()
  declare totalAmount: number

  @column()
  declare status: string

  @column()
  declare idempotencyKey: string

  @column()
  declare erpJobId: string | null

  /**
   * Payment gateway authorisation reference (e.g. txn-01JVXY...).
   * Populated when status transitions to PAID. NULL for orders that
   * fail before payment is authorised.
   */
  @column()
  declare transactionId: string | null

  @column()
  declare failureReason: string | null

  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime

  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

// ──────────────────────────────────────────────────────────────────────────────
// stock_reservations
// ──────────────────────────────────────────────────────────────────────────────
export class StockReservationSchema extends BaseModel {
  @column({ isPrimary: true })
  declare id: string

  @column()
  declare orderId: string

  @column()
  declare productId: string

  @column()
  declare quantity: number

  @column.dateTime()
  declare expiresAt: DateTime

  @column.dateTime()
  declare releasedAt: DateTime | null

  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime

  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}
